import Head from 'next/head'
import Image from 'next/image'
import { magic } from "../libs/magic";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [metadata, setMetadata] = useState()

  useEffect(() => {
    magic.user.isLoggedIn().then((boolean) => {
      if (boolean) {
        magic.user.getMetadata().then((data) => {
          setMetadata(data)
        })
      } else {
        console.log('user is not logged in')
      }
    })
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hello
      </main>
    </>
  )
}
